spring:
  datasource:
    url: "jdbc:mysql://192.168.50.102:3306/study"
    username: "mac"
    password: "mac"
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        jdbc.lob.non_contextual_creation: true
  thymeleaf:
    cache: false
  main:
    allow-bean-definition-overriding: true
#서버를 기동하지않고도 화면에서 변경된 데이터 확인가능. 별도 설정 필요
#spring.devtools.livereload.enabled=true
#spring.devtools.restart.enabled=true